// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/fulfillment-service/internal/idp (interfaces: ResourceManagerInterface)
//
// Generated by this command:
//
//	mockgen -destination=resource_manager_mock.go -package=idp . ResourceManagerInterface
//

// Package idp is a generated GoMock package.
package idp

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockResourceManagerInterface is a mock of ResourceManagerInterface interface.
type MockResourceManagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockResourceManagerInterfaceMockRecorder
	isgomock struct{}
}

// MockResourceManagerInterfaceMockRecorder is the mock recorder for MockResourceManagerInterface.
type MockResourceManagerInterfaceMockRecorder struct {
	mock *MockResourceManagerInterface
}

// NewMockResourceManagerInterface creates a new mock instance.
func NewMockResourceManagerInterface(ctrl *gomock.Controller) *MockResourceManagerInterface {
	mock := &MockResourceManagerInterface{ctrl: ctrl}
	mock.recorder = &MockResourceManagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceManagerInterface) EXPECT() *MockResourceManagerInterfaceMockRecorder {
	return m.recorder
}

// AddUserToGroupByID mocks base method.
func (m *MockResourceManagerInterface) AddUserToGroupByID(ctx context.Context, tenant, username, groupID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserToGroupByID", ctx, tenant, username, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserToGroupByID indicates an expected call of AddUserToGroupByID.
func (mr *MockResourceManagerInterfaceMockRecorder) AddUserToGroupByID(ctx, tenant, username, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToGroupByID", reflect.TypeOf((*MockResourceManagerInterface)(nil).AddUserToGroupByID), ctx, tenant, username, groupID)
}

// AddUserToProjectGroup mocks base method.
func (m *MockResourceManagerInterface) AddUserToProjectGroup(ctx context.Context, tenant, projectName, username, groupType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserToProjectGroup", ctx, tenant, projectName, username, groupType)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserToProjectGroup indicates an expected call of AddUserToProjectGroup.
func (mr *MockResourceManagerInterfaceMockRecorder) AddUserToProjectGroup(ctx, tenant, projectName, username, groupType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToProjectGroup", reflect.TypeOf((*MockResourceManagerInterface)(nil).AddUserToProjectGroup), ctx, tenant, projectName, username, groupType)
}

// CreateProjectGroups mocks base method.
func (m *MockResourceManagerInterface) CreateProjectGroups(ctx context.Context, tenant, projectName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProjectGroups", ctx, tenant, projectName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProjectGroups indicates an expected call of CreateProjectGroups.
func (mr *MockResourceManagerInterfaceMockRecorder) CreateProjectGroups(ctx, tenant, projectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProjectGroups", reflect.TypeOf((*MockResourceManagerInterface)(nil).CreateProjectGroups), ctx, tenant, projectName)
}

// DeleteProjectGroups mocks base method.
func (m *MockResourceManagerInterface) DeleteProjectGroups(ctx context.Context, tenant, projectName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProjectGroups", ctx, tenant, projectName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProjectGroups indicates an expected call of DeleteProjectGroups.
func (mr *MockResourceManagerInterfaceMockRecorder) DeleteProjectGroups(ctx, tenant, projectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProjectGroups", reflect.TypeOf((*MockResourceManagerInterface)(nil).DeleteProjectGroups), ctx, tenant, projectName)
}

// RemoveUserFromProjectGroup mocks base method.
func (m *MockResourceManagerInterface) RemoveUserFromProjectGroup(ctx context.Context, tenant, projectName, username, groupType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserFromProjectGroup", ctx, tenant, projectName, username, groupType)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserFromProjectGroup indicates an expected call of RemoveUserFromProjectGroup.
func (mr *MockResourceManagerInterfaceMockRecorder) RemoveUserFromProjectGroup(ctx, tenant, projectName, username, groupType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserFromProjectGroup", reflect.TypeOf((*MockResourceManagerInterface)(nil).RemoveUserFromProjectGroup), ctx, tenant, projectName, username, groupType)
}
