{{/*
Copyright (c) 2026 Red Hat Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
*/}}

apiVersion: v1
kind: Pod
metadata:
  namespace: {{ .Release.Namespace }}
  name: kafka
  labels:
    app: kafka
spec:
  volumes:
  - name: server-cert
    secret:
      secretName: kafka-server-cert
      defaultMode: 0440
  - name: config
    configMap:
      name: kafka-config
  - name: data
    emptyDir: {}
  - name: logs
    emptyDir: {}
  initContainers:
  - name: format-storage
    image: "{{ .Values.images.kafka }}"
    imagePullPolicy: IfNotPresent
    command:
    - /opt/kafka/bin/kafka-storage.sh
    - format
    - --config
    - /config/server.properties
    - --cluster-id
    - osac
    - --ignore-formatted
    - --add-scram
    - SCRAM-SHA-512=[name={{ .Values.sasl.username }},password={{ .Values.sasl.password }}]
    volumeMounts:
    - name: config
      mountPath: /config/server.properties
      subPath: server.properties
    - name: data
      mountPath: /data/kafka
  containers:
  - name: kafka
    image: "{{ .Values.images.kafka }}"
    imagePullPolicy: IfNotPresent
    command:
    - /opt/kafka/bin/kafka-server-start.sh
    - /config/server.properties
    volumeMounts:
    - name: data
      mountPath: /data/kafka
    - name: logs
      mountPath: /opt/kafka/logs
    - name: server-cert
      mountPath: /secrets/cert
    - name: config
      mountPath: /config/server.properties
      subPath: server.properties
    ports:
    - name: sasl-ssl
      protocol: TCP
      containerPort: 8000
    livenessProbe:
      tcpSocket:
        port: sasl-ssl
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      tcpSocket:
        port: sasl-ssl
      initialDelaySeconds: 15
      periodSeconds: 5
