//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: fulfillment/v1/host_type.proto

//go:build !protoopaque

package fulfillmentv1

import (
	v1 "github.com/innabox/fulfillment-service/internal/api/shared/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents the power state of a host.
type HostPowerState int32

const (
	// Unspecified indicates that the state is unknown.
	HostPowerState_HOST_POWER_STATE_UNSPECIFIED HostPowerState = 0
	// Indicates that the host is powered on.
	HostPowerState_HOST_POWER_STATE_ON HostPowerState = 1
	// Indicates that the host is powered off.
	HostPowerState_HOST_POWER_STATE_OFF HostPowerState = 2
)

// Enum value maps for HostPowerState.
var (
	HostPowerState_name = map[int32]string{
		0: "HOST_POWER_STATE_UNSPECIFIED",
		1: "HOST_POWER_STATE_ON",
		2: "HOST_POWER_STATE_OFF",
	}
	HostPowerState_value = map[string]int32{
		"HOST_POWER_STATE_UNSPECIFIED": 0,
		"HOST_POWER_STATE_ON":          1,
		"HOST_POWER_STATE_OFF":         2,
	}
)

func (x HostPowerState) Enum() *HostPowerState {
	p := new(HostPowerState)
	*p = x
	return p
}

func (x HostPowerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HostPowerState) Descriptor() protoreflect.EnumDescriptor {
	return file_fulfillment_v1_host_type_proto_enumTypes[0].Descriptor()
}

func (HostPowerState) Type() protoreflect.EnumType {
	return &file_fulfillment_v1_host_type_proto_enumTypes[0]
}

func (x HostPowerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Contains the details of the host.
//
// The `spec` contains the desired details, and may be modified by the user. The `status` contains the current status of
// the host, is provided by the system and can't be modified by the user.
type Host struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Unique identifier of the host.
	Id            string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata      *v1.Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *HostSpec    `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *HostStatus  `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_fulfillment_v1_host_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_v1_host_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Host) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Host) GetMetadata() *v1.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Host) GetSpec() *HostSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Host) GetStatus() *HostStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Host) SetId(v string) {
	x.Id = v
}

func (x *Host) SetMetadata(v *v1.Metadata) {
	x.Metadata = v
}

func (x *Host) SetSpec(v *HostSpec) {
	x.Spec = v
}

func (x *Host) SetStatus(v *HostStatus) {
	x.Status = v
}

func (x *Host) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *Host) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.Spec != nil
}

func (x *Host) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.Status != nil
}

func (x *Host) ClearMetadata() {
	x.Metadata = nil
}

func (x *Host) ClearSpec() {
	x.Spec = nil
}

func (x *Host) ClearStatus() {
	x.Status = nil
}

type Host_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the host.
	Id       string
	Metadata *v1.Metadata
	Spec     *HostSpec
	Status   *HostStatus
}

func (b0 Host_builder) Build() *Host {
	m0 := &Host{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Metadata = b.Metadata
	x.Spec = b.Spec
	x.Status = b.Status
	return m0
}

// The spec contains the details of the host as desired by the user.
type HostSpec struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Desired power state
	PowerState    HostPowerState `protobuf:"varint,1,opt,name=power_state,json=powerState,proto3,enum=fulfillment.v1.HostPowerState" json:"power_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostSpec) Reset() {
	*x = HostSpec{}
	mi := &file_fulfillment_v1_host_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostSpec) ProtoMessage() {}

func (x *HostSpec) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_v1_host_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HostSpec) GetPowerState() HostPowerState {
	if x != nil {
		return x.PowerState
	}
	return HostPowerState_HOST_POWER_STATE_UNSPECIFIED
}

func (x *HostSpec) SetPowerState(v HostPowerState) {
	x.PowerState = v
}

type HostSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Desired power state
	PowerState HostPowerState
}

func (b0 HostSpec_builder) Build() *HostSpec {
	m0 := &HostSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.PowerState = b.PowerState
	return m0
}

// The spec contains the details of the host as desired by the user.
type HostStatus struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Current power state
	PowerState    HostPowerState `protobuf:"varint,1,opt,name=power_state,json=powerState,proto3,enum=fulfillment.v1.HostPowerState" json:"power_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostStatus) Reset() {
	*x = HostStatus{}
	mi := &file_fulfillment_v1_host_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostStatus) ProtoMessage() {}

func (x *HostStatus) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_v1_host_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HostStatus) GetPowerState() HostPowerState {
	if x != nil {
		return x.PowerState
	}
	return HostPowerState_HOST_POWER_STATE_UNSPECIFIED
}

func (x *HostStatus) SetPowerState(v HostPowerState) {
	x.PowerState = v
}

type HostStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Current power state
	PowerState HostPowerState
}

func (b0 HostStatus_builder) Build() *HostStatus {
	m0 := &HostStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.PowerState = b.PowerState
	return m0
}

var File_fulfillment_v1_host_type_proto protoreflect.FileDescriptor

var file_fulfillment_v1_host_type_proto_rawDesc = string([]byte{
	0x0a, 0x1e, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31,
	0x2f, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0e, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31,
	0x1a, 0x1d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xa9, 0x01, 0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2f, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2c, 0x0a, 0x04, 0x73, 0x70, 0x65,
	0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c,
	0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x70, 0x65,
	0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x32, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c,
	0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4b, 0x0a, 0x08, 0x48,
	0x6f, 0x73, 0x74, 0x53, 0x70, 0x65, 0x63, 0x12, 0x3f, 0x0a, 0x0b, 0x70, 0x6f, 0x77, 0x65, 0x72,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x66,
	0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f,
	0x73, 0x74, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0a, 0x70, 0x6f,
	0x77, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x4d, 0x0a, 0x0a, 0x48, 0x6f, 0x73, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3f, 0x0a, 0x0b, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x66, 0x75,
	0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x73,
	0x74, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0a, 0x70, 0x6f, 0x77,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2a, 0x65, 0x0a, 0x0e, 0x48, 0x6f, 0x73, 0x74, 0x50,
	0x6f, 0x77, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x1c, 0x48, 0x4f, 0x53,
	0x54, 0x5f, 0x50, 0x4f, 0x57, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x48,
	0x4f, 0x53, 0x54, 0x5f, 0x50, 0x4f, 0x57, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x4f, 0x4e, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x48, 0x4f, 0x53, 0x54, 0x5f, 0x50, 0x4f, 0x57,
	0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x4f, 0x46, 0x46, 0x10, 0x02, 0x42, 0xce,
	0x01, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x76, 0x31, 0x42, 0x0d, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x50, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x69, 0x6e, 0x6e, 0x61, 0x62, 0x6f, 0x78, 0x2f, 0x66, 0x75, 0x6c, 0x66, 0x69,
	0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x75, 0x6c, 0x66,
	0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x66, 0x75, 0x6c, 0x66, 0x69,
	0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x46, 0x58, 0x58, 0xaa, 0x02,
	0x0e, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x31, 0xca,
	0x02, 0x0e, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x5c, 0x56, 0x31,
	0xe2, 0x02, 0x1a, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x5c, 0x56,
	0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0f,
	0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x3a, 0x3a, 0x56, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_fulfillment_v1_host_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fulfillment_v1_host_type_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_fulfillment_v1_host_type_proto_goTypes = []any{
	(HostPowerState)(0), // 0: fulfillment.v1.HostPowerState
	(*Host)(nil),        // 1: fulfillment.v1.Host
	(*HostSpec)(nil),    // 2: fulfillment.v1.HostSpec
	(*HostStatus)(nil),  // 3: fulfillment.v1.HostStatus
	(*v1.Metadata)(nil), // 4: shared.v1.Metadata
}
var file_fulfillment_v1_host_type_proto_depIdxs = []int32{
	4, // 0: fulfillment.v1.Host.metadata:type_name -> shared.v1.Metadata
	2, // 1: fulfillment.v1.Host.spec:type_name -> fulfillment.v1.HostSpec
	3, // 2: fulfillment.v1.Host.status:type_name -> fulfillment.v1.HostStatus
	0, // 3: fulfillment.v1.HostSpec.power_state:type_name -> fulfillment.v1.HostPowerState
	0, // 4: fulfillment.v1.HostStatus.power_state:type_name -> fulfillment.v1.HostPowerState
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_fulfillment_v1_host_type_proto_init() }
func file_fulfillment_v1_host_type_proto_init() {
	if File_fulfillment_v1_host_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fulfillment_v1_host_type_proto_rawDesc), len(file_fulfillment_v1_host_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fulfillment_v1_host_type_proto_goTypes,
		DependencyIndexes: file_fulfillment_v1_host_type_proto_depIdxs,
		EnumInfos:         file_fulfillment_v1_host_type_proto_enumTypes,
		MessageInfos:      file_fulfillment_v1_host_type_proto_msgTypes,
	}.Build()
	File_fulfillment_v1_host_type_proto = out.File
	file_fulfillment_v1_host_type_proto_goTypes = nil
	file_fulfillment_v1_host_type_proto_depIdxs = nil
}
