// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/fulfillment-service/internal/api/osac/private/v1 (interfaces: ComputeInstanceTemplatesClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/clients/mock_compute_instance_templates_client.go -package=clients github.com/osac-project/fulfillment-service/internal/api/osac/private/v1 ComputeInstanceTemplatesClient
//

// Package clients is a generated GoMock package.
package clients

import (
	context "context"
	reflect "reflect"

	privatev1 "github.com/osac-project/fulfillment-service/internal/api/osac/private/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockComputeInstanceTemplatesClient is a mock of ComputeInstanceTemplatesClient interface.
type MockComputeInstanceTemplatesClient struct {
	ctrl     *gomock.Controller
	recorder *MockComputeInstanceTemplatesClientMockRecorder
	isgomock struct{}
}

// MockComputeInstanceTemplatesClientMockRecorder is the mock recorder for MockComputeInstanceTemplatesClient.
type MockComputeInstanceTemplatesClientMockRecorder struct {
	mock *MockComputeInstanceTemplatesClient
}

// NewMockComputeInstanceTemplatesClient creates a new mock instance.
func NewMockComputeInstanceTemplatesClient(ctrl *gomock.Controller) *MockComputeInstanceTemplatesClient {
	mock := &MockComputeInstanceTemplatesClient{ctrl: ctrl}
	mock.recorder = &MockComputeInstanceTemplatesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComputeInstanceTemplatesClient) EXPECT() *MockComputeInstanceTemplatesClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockComputeInstanceTemplatesClient) Create(ctx context.Context, in *privatev1.ComputeInstanceTemplatesCreateRequest, opts ...grpc.CallOption) (*privatev1.ComputeInstanceTemplatesCreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*privatev1.ComputeInstanceTemplatesCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockComputeInstanceTemplatesClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockComputeInstanceTemplatesClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockComputeInstanceTemplatesClient) Delete(ctx context.Context, in *privatev1.ComputeInstanceTemplatesDeleteRequest, opts ...grpc.CallOption) (*privatev1.ComputeInstanceTemplatesDeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*privatev1.ComputeInstanceTemplatesDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockComputeInstanceTemplatesClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockComputeInstanceTemplatesClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockComputeInstanceTemplatesClient) Get(ctx context.Context, in *privatev1.ComputeInstanceTemplatesGetRequest, opts ...grpc.CallOption) (*privatev1.ComputeInstanceTemplatesGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*privatev1.ComputeInstanceTemplatesGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockComputeInstanceTemplatesClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockComputeInstanceTemplatesClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockComputeInstanceTemplatesClient) List(ctx context.Context, in *privatev1.ComputeInstanceTemplatesListRequest, opts ...grpc.CallOption) (*privatev1.ComputeInstanceTemplatesListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*privatev1.ComputeInstanceTemplatesListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockComputeInstanceTemplatesClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockComputeInstanceTemplatesClient)(nil).List), varargs...)
}

// Signal mocks base method.
func (m *MockComputeInstanceTemplatesClient) Signal(ctx context.Context, in *privatev1.ComputeInstanceTemplatesSignalRequest, opts ...grpc.CallOption) (*privatev1.ComputeInstanceTemplatesSignalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Signal", varargs...)
	ret0, _ := ret[0].(*privatev1.ComputeInstanceTemplatesSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockComputeInstanceTemplatesClientMockRecorder) Signal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockComputeInstanceTemplatesClient)(nil).Signal), varargs...)
}

// Update mocks base method.
func (m *MockComputeInstanceTemplatesClient) Update(ctx context.Context, in *privatev1.ComputeInstanceTemplatesUpdateRequest, opts ...grpc.CallOption) (*privatev1.ComputeInstanceTemplatesUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*privatev1.ComputeInstanceTemplatesUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockComputeInstanceTemplatesClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockComputeInstanceTemplatesClient)(nil).Update), varargs...)
}
