// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/fulfillment-service/internal/api/osac/private/v1 (interfaces: ClusterTemplatesClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/clients/mock_cluster_templates_client.go -package=clients github.com/osac-project/fulfillment-service/internal/api/osac/private/v1 ClusterTemplatesClient
//

// Package clients is a generated GoMock package.
package clients

import (
	context "context"
	reflect "reflect"

	privatev1 "github.com/osac-project/fulfillment-service/internal/api/osac/private/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockClusterTemplatesClient is a mock of ClusterTemplatesClient interface.
type MockClusterTemplatesClient struct {
	ctrl     *gomock.Controller
	recorder *MockClusterTemplatesClientMockRecorder
	isgomock struct{}
}

// MockClusterTemplatesClientMockRecorder is the mock recorder for MockClusterTemplatesClient.
type MockClusterTemplatesClientMockRecorder struct {
	mock *MockClusterTemplatesClient
}

// NewMockClusterTemplatesClient creates a new mock instance.
func NewMockClusterTemplatesClient(ctrl *gomock.Controller) *MockClusterTemplatesClient {
	mock := &MockClusterTemplatesClient{ctrl: ctrl}
	mock.recorder = &MockClusterTemplatesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterTemplatesClient) EXPECT() *MockClusterTemplatesClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockClusterTemplatesClient) Create(ctx context.Context, in *privatev1.ClusterTemplatesCreateRequest, opts ...grpc.CallOption) (*privatev1.ClusterTemplatesCreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*privatev1.ClusterTemplatesCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockClusterTemplatesClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClusterTemplatesClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockClusterTemplatesClient) Delete(ctx context.Context, in *privatev1.ClusterTemplatesDeleteRequest, opts ...grpc.CallOption) (*privatev1.ClusterTemplatesDeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*privatev1.ClusterTemplatesDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockClusterTemplatesClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClusterTemplatesClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockClusterTemplatesClient) Get(ctx context.Context, in *privatev1.ClusterTemplatesGetRequest, opts ...grpc.CallOption) (*privatev1.ClusterTemplatesGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*privatev1.ClusterTemplatesGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockClusterTemplatesClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClusterTemplatesClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockClusterTemplatesClient) List(ctx context.Context, in *privatev1.ClusterTemplatesListRequest, opts ...grpc.CallOption) (*privatev1.ClusterTemplatesListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*privatev1.ClusterTemplatesListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockClusterTemplatesClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockClusterTemplatesClient)(nil).List), varargs...)
}

// Signal mocks base method.
func (m *MockClusterTemplatesClient) Signal(ctx context.Context, in *privatev1.ClusterTemplatesSignalRequest, opts ...grpc.CallOption) (*privatev1.ClusterTemplatesSignalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Signal", varargs...)
	ret0, _ := ret[0].(*privatev1.ClusterTemplatesSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockClusterTemplatesClientMockRecorder) Signal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockClusterTemplatesClient)(nil).Signal), varargs...)
}

// Update mocks base method.
func (m *MockClusterTemplatesClient) Update(ctx context.Context, in *privatev1.ClusterTemplatesUpdateRequest, opts ...grpc.CallOption) (*privatev1.ClusterTemplatesUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*privatev1.ClusterTemplatesUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockClusterTemplatesClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClusterTemplatesClient)(nil).Update), varargs...)
}
