#
# Copyright (c) 2026 Red Hat Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#

# Certificate configuration:
certs:

  # This defines the cert-manager issuer that will be used for the server TLS certificate. The default is to use a
  # cluster wide issuer, but there is no default value for the name, so it must be set.
  issuerRef:
    kind: ClusterIssuer
    name:

# Image configuration:
images:
  kafka: quay.io/strimzi/kafka:1.0.0-kafka-4.2.0

# SASL/PLAIN credentials:
sasl:
  username: admin
  password: admin-secret
