// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api/osac/private/v1/organizations_service_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=../../api/osac/private/v1/organizations_service_grpc.pb.go -destination=organizations_client_mock.go -package=tenant OrganizationsClient
//

// Package tenant is a generated GoMock package.
package onboarding

import (
	context "context"
	reflect "reflect"

	privatev1 "github.com/osac-project/fulfillment-service/internal/api/osac/private/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockOrganizationsClient is a mock of OrganizationsClient interface.
type MockOrganizationsClient struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationsClientMockRecorder
	isgomock struct{}
}

// MockOrganizationsClientMockRecorder is the mock recorder for MockOrganizationsClient.
type MockOrganizationsClientMockRecorder struct {
	mock *MockOrganizationsClient
}

// NewMockOrganizationsClient creates a new mock instance.
func NewMockOrganizationsClient(ctrl *gomock.Controller) *MockOrganizationsClient {
	mock := &MockOrganizationsClient{ctrl: ctrl}
	mock.recorder = &MockOrganizationsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationsClient) EXPECT() *MockOrganizationsClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrganizationsClient) Create(ctx context.Context, in *privatev1.OrganizationsCreateRequest, opts ...grpc.CallOption) (*privatev1.OrganizationsCreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*privatev1.OrganizationsCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOrganizationsClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrganizationsClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockOrganizationsClient) Delete(ctx context.Context, in *privatev1.OrganizationsDeleteRequest, opts ...grpc.CallOption) (*privatev1.OrganizationsDeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*privatev1.OrganizationsDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockOrganizationsClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrganizationsClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockOrganizationsClient) Get(ctx context.Context, in *privatev1.OrganizationsGetRequest, opts ...grpc.CallOption) (*privatev1.OrganizationsGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*privatev1.OrganizationsGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOrganizationsClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOrganizationsClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockOrganizationsClient) List(ctx context.Context, in *privatev1.OrganizationsListRequest, opts ...grpc.CallOption) (*privatev1.OrganizationsListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*privatev1.OrganizationsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockOrganizationsClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOrganizationsClient)(nil).List), varargs...)
}

// Signal mocks base method.
func (m *MockOrganizationsClient) Signal(ctx context.Context, in *privatev1.OrganizationsSignalRequest, opts ...grpc.CallOption) (*privatev1.OrganizationsSignalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Signal", varargs...)
	ret0, _ := ret[0].(*privatev1.OrganizationsSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockOrganizationsClientMockRecorder) Signal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockOrganizationsClient)(nil).Signal), varargs...)
}

// Update mocks base method.
func (m *MockOrganizationsClient) Update(ctx context.Context, in *privatev1.OrganizationsUpdateRequest, opts ...grpc.CallOption) (*privatev1.OrganizationsUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*privatev1.OrganizationsUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockOrganizationsClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrganizationsClient)(nil).Update), varargs...)
}

// MockOrganizationsServer is a mock of OrganizationsServer interface.
type MockOrganizationsServer struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationsServerMockRecorder
	isgomock struct{}
}

// MockOrganizationsServerMockRecorder is the mock recorder for MockOrganizationsServer.
type MockOrganizationsServerMockRecorder struct {
	mock *MockOrganizationsServer
}

// NewMockOrganizationsServer creates a new mock instance.
func NewMockOrganizationsServer(ctrl *gomock.Controller) *MockOrganizationsServer {
	mock := &MockOrganizationsServer{ctrl: ctrl}
	mock.recorder = &MockOrganizationsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationsServer) EXPECT() *MockOrganizationsServerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrganizationsServer) Create(arg0 context.Context, arg1 *privatev1.OrganizationsCreateRequest) (*privatev1.OrganizationsCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.OrganizationsCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOrganizationsServerMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrganizationsServer)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockOrganizationsServer) Delete(arg0 context.Context, arg1 *privatev1.OrganizationsDeleteRequest) (*privatev1.OrganizationsDeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.OrganizationsDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockOrganizationsServerMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrganizationsServer)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockOrganizationsServer) Get(arg0 context.Context, arg1 *privatev1.OrganizationsGetRequest) (*privatev1.OrganizationsGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.OrganizationsGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOrganizationsServerMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOrganizationsServer)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockOrganizationsServer) List(arg0 context.Context, arg1 *privatev1.OrganizationsListRequest) (*privatev1.OrganizationsListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.OrganizationsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockOrganizationsServerMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOrganizationsServer)(nil).List), arg0, arg1)
}

// Signal mocks base method.
func (m *MockOrganizationsServer) Signal(arg0 context.Context, arg1 *privatev1.OrganizationsSignalRequest) (*privatev1.OrganizationsSignalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.OrganizationsSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockOrganizationsServerMockRecorder) Signal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockOrganizationsServer)(nil).Signal), arg0, arg1)
}

// Update mocks base method.
func (m *MockOrganizationsServer) Update(arg0 context.Context, arg1 *privatev1.OrganizationsUpdateRequest) (*privatev1.OrganizationsUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.OrganizationsUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockOrganizationsServerMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrganizationsServer)(nil).Update), arg0, arg1)
}

// mustEmbedUnimplementedOrganizationsServer mocks base method.
func (m *MockOrganizationsServer) mustEmbedUnimplementedOrganizationsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedOrganizationsServer")
}

// mustEmbedUnimplementedOrganizationsServer indicates an expected call of mustEmbedUnimplementedOrganizationsServer.
func (mr *MockOrganizationsServerMockRecorder) mustEmbedUnimplementedOrganizationsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedOrganizationsServer", reflect.TypeOf((*MockOrganizationsServer)(nil).mustEmbedUnimplementedOrganizationsServer))
}

// MockUnsafeOrganizationsServer is a mock of UnsafeOrganizationsServer interface.
type MockUnsafeOrganizationsServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeOrganizationsServerMockRecorder
	isgomock struct{}
}

// MockUnsafeOrganizationsServerMockRecorder is the mock recorder for MockUnsafeOrganizationsServer.
type MockUnsafeOrganizationsServerMockRecorder struct {
	mock *MockUnsafeOrganizationsServer
}

// NewMockUnsafeOrganizationsServer creates a new mock instance.
func NewMockUnsafeOrganizationsServer(ctrl *gomock.Controller) *MockUnsafeOrganizationsServer {
	mock := &MockUnsafeOrganizationsServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeOrganizationsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeOrganizationsServer) EXPECT() *MockUnsafeOrganizationsServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedOrganizationsServer mocks base method.
func (m *MockUnsafeOrganizationsServer) mustEmbedUnimplementedOrganizationsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedOrganizationsServer")
}

// mustEmbedUnimplementedOrganizationsServer indicates an expected call of mustEmbedUnimplementedOrganizationsServer.
func (mr *MockUnsafeOrganizationsServerMockRecorder) mustEmbedUnimplementedOrganizationsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedOrganizationsServer", reflect.TypeOf((*MockUnsafeOrganizationsServer)(nil).mustEmbedUnimplementedOrganizationsServer))
}
