- name: Allow reflection and health to everyone
  action: allow
  condition: method.startsWith('/grpc.reflection.') || method.startsWith('/grpc.health.')

- name: Allow specific methods to client
  action: allow
  condition: |
    subject.name == 'system:serviceaccount:innabox:client' &&
    method in [
      '/events.v1/Watch',
      '/fulfillment.v1.ClusterTemplates/Get',
      '/fulfillment.v1.ClusterTemplates/List',
      '/fulfillment.v1.Clusters/Create',
      '/fulfillment.v1.Clusters/Delete',
      '/fulfillment.v1.Clusters/Get',
      '/fulfillment.v1.Clusters/GetKubeconfig',
      '/fulfillment.v1.Clusters/GetKubeconfigViaHttp',
      '/fulfillment.v1.Clusters/GetPassword',
      '/fulfillment.v1.Clusters/GetPasswordViaHttp',
      '/fulfillment.v1.Clusters/List',
      '/fulfillment.v1.Clusters/Update',
      '/fulfillment.v1.HostClasses/Get',
      '/fulfillment.v1.HostClasses/List',
    ]

- name: Allow everything to admin and controller
  action: allow
  condition: |
    subject.name in [
      'system:serviceaccount:innabox:admin',
      'system:serviceaccount:innabox:controller',
      'system:serviceaccount:cloudkit-operator-system:cloudkit-operator-controller-manager',
    ]
