//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: osac/public/v1/baremetal_instance_templates_service.proto

package publicv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BareMetalInstanceTemplates_List_FullMethodName = "/osac.public.v1.BareMetalInstanceTemplates/List"
	BareMetalInstanceTemplates_Get_FullMethodName  = "/osac.public.v1.BareMetalInstanceTemplates/Get"
)

// BareMetalInstanceTemplatesClient is the client API for BareMetalInstanceTemplates service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BareMetalInstanceTemplatesClient interface {
	List(ctx context.Context, in *BareMetalInstanceTemplatesListRequest, opts ...grpc.CallOption) (*BareMetalInstanceTemplatesListResponse, error)
	Get(ctx context.Context, in *BareMetalInstanceTemplatesGetRequest, opts ...grpc.CallOption) (*BareMetalInstanceTemplatesGetResponse, error)
}

type bareMetalInstanceTemplatesClient struct {
	cc grpc.ClientConnInterface
}

func NewBareMetalInstanceTemplatesClient(cc grpc.ClientConnInterface) BareMetalInstanceTemplatesClient {
	return &bareMetalInstanceTemplatesClient{cc}
}

func (c *bareMetalInstanceTemplatesClient) List(ctx context.Context, in *BareMetalInstanceTemplatesListRequest, opts ...grpc.CallOption) (*BareMetalInstanceTemplatesListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BareMetalInstanceTemplatesListResponse)
	err := c.cc.Invoke(ctx, BareMetalInstanceTemplates_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bareMetalInstanceTemplatesClient) Get(ctx context.Context, in *BareMetalInstanceTemplatesGetRequest, opts ...grpc.CallOption) (*BareMetalInstanceTemplatesGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BareMetalInstanceTemplatesGetResponse)
	err := c.cc.Invoke(ctx, BareMetalInstanceTemplates_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BareMetalInstanceTemplatesServer is the server API for BareMetalInstanceTemplates service.
// All implementations must embed UnimplementedBareMetalInstanceTemplatesServer
// for forward compatibility.
type BareMetalInstanceTemplatesServer interface {
	List(context.Context, *BareMetalInstanceTemplatesListRequest) (*BareMetalInstanceTemplatesListResponse, error)
	Get(context.Context, *BareMetalInstanceTemplatesGetRequest) (*BareMetalInstanceTemplatesGetResponse, error)
	mustEmbedUnimplementedBareMetalInstanceTemplatesServer()
}

// UnimplementedBareMetalInstanceTemplatesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBareMetalInstanceTemplatesServer struct{}

func (UnimplementedBareMetalInstanceTemplatesServer) List(context.Context, *BareMetalInstanceTemplatesListRequest) (*BareMetalInstanceTemplatesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedBareMetalInstanceTemplatesServer) Get(context.Context, *BareMetalInstanceTemplatesGetRequest) (*BareMetalInstanceTemplatesGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedBareMetalInstanceTemplatesServer) mustEmbedUnimplementedBareMetalInstanceTemplatesServer() {
}
func (UnimplementedBareMetalInstanceTemplatesServer) testEmbeddedByValue() {}

// UnsafeBareMetalInstanceTemplatesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BareMetalInstanceTemplatesServer will
// result in compilation errors.
type UnsafeBareMetalInstanceTemplatesServer interface {
	mustEmbedUnimplementedBareMetalInstanceTemplatesServer()
}

func RegisterBareMetalInstanceTemplatesServer(s grpc.ServiceRegistrar, srv BareMetalInstanceTemplatesServer) {
	// If the following call pancis, it indicates UnimplementedBareMetalInstanceTemplatesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BareMetalInstanceTemplates_ServiceDesc, srv)
}

func _BareMetalInstanceTemplates_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BareMetalInstanceTemplatesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BareMetalInstanceTemplatesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BareMetalInstanceTemplates_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BareMetalInstanceTemplatesServer).List(ctx, req.(*BareMetalInstanceTemplatesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BareMetalInstanceTemplates_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BareMetalInstanceTemplatesGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BareMetalInstanceTemplatesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BareMetalInstanceTemplates_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BareMetalInstanceTemplatesServer).Get(ctx, req.(*BareMetalInstanceTemplatesGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BareMetalInstanceTemplates_ServiceDesc is the grpc.ServiceDesc for BareMetalInstanceTemplates service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BareMetalInstanceTemplates_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osac.public.v1.BareMetalInstanceTemplates",
	HandlerType: (*BareMetalInstanceTemplatesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _BareMetalInstanceTemplates_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _BareMetalInstanceTemplates_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osac/public/v1/baremetal_instance_templates_service.proto",
}
