apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    component: service

resources:
- authconfig.yaml
- certificate.yaml
- deployment.yaml
- service.yaml

configMapGenerator:
- files:
  - files/envoy.yaml
  name: fulfillment-service-envoy
