#
# Copyright (c) 2025 Red Hat Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

name: Publish image

on:
  push:
    branches:
    - main
    tags:
    - 'v*'

jobs:

  publish-image:
    name: Publish image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - run: |
        # Login to the registry:
        registry="ghcr.io"
        podman login --username "${{ github.actor }}" --password "${{ secrets.GITHUB_TOKEN }}" "${registry}"

        # Determine the image version:
        version="$(git describe --tags)"
        image="${registry}/${{ github.repository }}:${version}"

        # Build the image:
        podman build -t "${image}" .
        podman push "${image}"

        # Push the image again with the `latest` tag:
        latest="${registry}/${{ github.repository }}:latest"
        podman tag "${image}" "${latest}"
        podman push "${latest}"
